// <auto-generated />
using System;
using DesafioNetCore.Infra;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DesafioNetCore.Infra.Migrations.AppDb
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240104185109_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DesafioNetCore.Domain.Entities.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("AlternativeIdentifier")
                        .HasColumnType("text")
                        .HasColumnName("alternativeidentifier");

                    b.Property<bool>("CanBuy")
                        .HasColumnType("boolean")
                        .HasColumnName("canbuy");

                    b.Property<string>("Document")
                        .HasColumnType("text")
                        .HasColumnName("document");

                    b.Property<bool>("Enable")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Observations")
                        .HasColumnType("text")
                        .HasColumnName("observations");

                    b.Property<string>("Town")
                        .HasColumnType("text")
                        .HasColumnName("town");

                    b.HasKey("Id");

                    b.ToTable("person", "public");
                });

            modelBuilder.Entity("DesafioNetCore.Domain.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<bool>("Active")
                        .HasColumnType("boolean")
                        .HasColumnName("active");

                    b.Property<string>("BarCode")
                        .HasColumnType("text")
                        .HasColumnName("barcode");

                    b.Property<bool>("CanSell")
                        .HasColumnType("boolean")
                        .HasColumnName("cansell");

                    b.Property<string>("FullDescription")
                        .HasColumnType("text")
                        .HasColumnName("shortdescription");

                    b.Property<Guid>("IdUnit")
                        .HasColumnType("uuid")
                        .HasColumnName("acronym");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric")
                        .HasColumnName("price");

                    b.Property<string>("ShortDescription")
                        .HasColumnType("text")
                        .HasColumnName("fulldescription");

                    b.Property<decimal>("Storage")
                        .HasColumnType("numeric")
                        .HasColumnName("storage");

                    b.Property<Guid?>("UnitId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("IdUnit");

                    b.HasIndex("UnitId");

                    b.ToTable("product", "public");
                });

            modelBuilder.Entity("DesafioNetCore.Domain.Entities.Unit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Acronym")
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Units", "public");
                });

            modelBuilder.Entity("DesafioNetCore.Domain.Entities.Product", b =>
                {
                    b.HasOne("DesafioNetCore.Domain.Entities.Unit", "Unit")
                        .WithMany()
                        .HasForeignKey("IdUnit")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DesafioNetCore.Domain.Entities.Unit", null)
                        .WithMany("Products")
                        .HasForeignKey("UnitId");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("DesafioNetCore.Domain.Entities.Unit", b =>
                {
                    b.Navigation("Products");
                });
#pragma warning restore 612, 618
        }
    }
}
